version: "3.9"

services:
  db:
    image: postgres:16
    container_name: finapp-db
    restart: always
    environment:
      POSTGRES_USER: finapp
      POSTGRES_PASSWORD: finapp
      POSTGRES_DB: finapp
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: finapp-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"
